image: debian:10.10

build:
  stage: build
  tags:
    - docker
    - linux
  script:
    - cat /etc/os-release
    - cat /etc/debian_version
    - ls -la /
    - mount
    - uname -a
    - ip addr
    - ip route
    - whoami
    - id
    - apt-get update && apt-get install -y debootstrap squashfs-tools xorriso isolinux syslinux-efi grub-pc-bin grub-efi-amd64-bin mtools dosfstools
    - mkdir -p /distribution_content/chroot
    - debootstrap --arch=amd64 --components=main,non-free --variant=minbase stable /distribution_content/chroot http://ftp.ro.debian.org/debian/
#  artifacts:
#    paths:
#      - mybinary
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"
