# ============================================================================ #
# Author: Tancredi-Paul Grozav <paul@grozav.info>
# ============================================================================ #
# This is the only place where the base image version is defined.Then read in sh
image: debian:12.1
# ============================================================================ #
core__build__pxe_kernel:
  stage: build
  tags:
    - container
    - linux
  script:
    - ./aleph.sh --core__build__pxe_kernel
  artifacts:
    paths:
      - distribution_content/aleph.krnl
      - distribution_content/aleph.ird
    expire_in: 1 hour
# ============================================================================ #
core__build__squashfs:
  stage: build
  tags:
    - container
    - linux
  script:
    - ./aleph.sh --core__build__squashfs
  artifacts:
    paths:
      - distribution_content/aleph.sfs
    expire_in: 1 hour
      # depending on your build setup it's most likely a good idea to cache
      #   outputs to reduce the build time:
      # cache:
      #   paths:
      #     - "*.o"
# ============================================================================ #
core__build__iso:
  stage: build
  tags:
    - container
    - linux
  needs:
    - core__build__squashfs
  script:
    - ./aleph.sh --core__build__iso
  artifacts:
    paths:
      - distribution_content/aleph.iso
    expire_in: 1 hour
# ============================================================================ #
pages:
  stage: deploy
  needs:
    - core__build__pxe_kernel
    - core__build__squashfs
    - core__build__iso
  script:
    - ./aleph.sh --core__publish
  artifacts:
    paths:
      - public/
    expire_in: 1 hour
# ============================================================================ #

