#!/bin/bash
# ============================================================================ #
# Author: Tancredi-Paul Grozav <paul@grozav.info>
# ============================================================================ #
mountroot()
{
  # run udevadm
  wait_for_udev 10

  # parse kernel cmdline args.
  for x in $(cat /proc/cmdline); do
    case ${x} in
    config_srv_url=*)
      export config_srv_url=${x#config_srv_url=}
      ;;
    esac
  done

  log_begin_msg "Configure network"
  configure_networking || panic "Can't configure network"
  log_success_msg "Network configured"

  # Request script after network is up
  log_begin_msg "Request ird_net script" && echo
  (
    wget -O /tmp/script.sh ${config_srv_url}/ird_net &&
    source /tmp/script.sh &&
    rm -f /tmp/script.sh
  ) || panic "Error running ird_net script"
  log_success_msg "Script ird_net ended"
}
# ============================================================================ #

