#!/bin/bash
# ============================================================================ #
# Author(s):
# - Tancredi-Paul Grozav <paul@grozav.info>
# ============================================================================ #
# Use this to generate the type enforcement file.
# ============================================================================ #
should_debug=0 &&
should_debug=1 && # Uncomment to enable debugging
# Start debugging
[ ${should_debug} -eq 1 ] && set -x || true &&
script_dir="$( cd $( dirname ${0} ) && pwd )" &&
policy_name="aleph_policy" &&
exit_code=0 &&
# ============================================================================ #
remote_host="${1}" &&
if [ "${remote_host}" == "" ]
then
  echo "Please provide a remote host with SELinux to generate the TE file" &&
  exit_code=1 &&
  # Stop debugging
  [ ${should_debug} -eq 1 ] && set +x || true &&
  exit ${exit_code}
fi &&

# dnf install -y policycoreutils-python-utils
# cat ${script_dir}/auditd.log |
#   ssh -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
#   ${remote_host} audit2allow -m ${policy_name} \
#   > ${script_dir}/${policy_name}.te &&

echo "Removing comments" &&
cat ${script_dir}/${policy_name}.te | grep -v "^#" | grep . | sed 's/\t/  /g' \
  > ${script_dir}/${policy_name}.tmp &&
mv -f ${script_dir}/${policy_name}.tmp ${script_dir}/${policy_name}.te &&

echo "Adding header" &&
(
  (cat - << EOF
# ============================================================================ #
# Author(s):
# - Tancredi-Paul Grozav <paul@grozav.info>
#
# This file is generated with bash generate.sh hostname
# Do not edit this file manually ! The changes will be lost !
# ============================================================================ #
EOF
  ) &&
  cat ${script_dir}/${policy_name}.te &&
  (cat - << EOF
# ============================================================================ #
EOF
  ) &&
  true
) > ${script_dir}/${policy_name}.tmp &&
mv -f ${script_dir}/${policy_name}.tmp ${script_dir}/${policy_name}.te &&

echo "Sorting type declarations" &&
(
  cat ${script_dir}/${policy_name}.te | sed '/^require {/q' &&
  cat ${script_dir}/${policy_name}.te | grep "^  type " | sort &&
  cat ${script_dir}/${policy_name}.te | sed -n '/^  class /,$p' &&
  true
) > ${script_dir}/${policy_name}.tmp &&
mv -f ${script_dir}/${policy_name}.tmp ${script_dir}/${policy_name}.te &&
# checkmodule -M -m -o aleph_policy.mod aleph_policy.te
# semodule_package -o aleph_policy.pp -m aleph_policy.mod
# semodule -i aleph_policy.pp
# ============================================================================ #
# Stop debugging
[ ${should_debug} -eq 1 ] && set +x || true &&
exit ${exit_code}
# ============================================================================ #
